"""
1.0.3

Revision ID: c76c9a1f52dc
Revises: d8dccb5dc598
Branch Labels:
Depends On:
Create Date: 2025-11-09 13:49:56.053199

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
db_version = "1.0.3"
revision = "c76c9a1f52dc"
down_revision = "d8dccb5dc598"
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    if not inspector.has_table("open_files"):
        op.create_table(
            "open_files",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("parent_id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(length=255), nullable=True),
            sa.Column("sha1", sa.String(length=40), nullable=True),
            sa.Column("size", sa.BigInteger(), nullable=True),
            sa.Column("pick_code", sa.String(length=50), nullable=True),
            sa.Column("ico", sa.String(length=40), nullable=True),
            sa.Column("ctime", sa.BigInteger(), nullable=True),
            sa.Column("mtime", sa.BigInteger(), nullable=True),
            sa.Column("utime", sa.BigInteger(), nullable=True),
            sa.Column("file_type", sa.BigInteger(), nullable=True),
            sa.Column("type", sa.BigInteger(), nullable=True),
            sa.Column("path", sa.Text(), nullable=True),
            sa.Column("local_path", sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("path"),
        )
    if not inspector.has_table("open_folders"):
        op.create_table(
            "open_folders",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("parent_id", sa.Integer(), nullable=False),
            sa.Column("name", sa.String(length=255), nullable=True),
            sa.Column("path", sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("path"),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    if inspector.has_table("open_files"):
        op.drop_table("open_folders")
    if inspector.has_table("open_folders"):
        op.drop_table("open_files")
    # ### end Alembic commands ###
