"""
1.0.2

Revision ID: d8dccb5dc598
Revises: 2606909750bf
Branch Labels:
Depends On:
Create Date: 2025-10-12 12:36:04.347486

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
db_version = "1.0.2"
revision = "d8dccb5dc598"
down_revision = "2606909750bf"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # 检查 life_event 表是否存在
    if not inspector.has_table("life_event"):
        op.create_table(
            "life_event",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("type", sa.Integer(), nullable=False),
            sa.Column("file_id", sa.Integer(), nullable=False),
            sa.Column("parent_id", sa.Integer(), nullable=False),
            sa.Column("file_name", sa.String(length=255), nullable=True),
            sa.Column("file_category", sa.Integer(), nullable=False),
            sa.Column("file_type", sa.Integer(), nullable=False),
            sa.Column("file_size", sa.BigInteger(), nullable=True),
            sa.Column("sha1", sa.String(length=40), nullable=True),
            sa.Column("pick_code", sa.String(length=50), nullable=True),
            sa.Column("update_time", sa.BigInteger(), nullable=True),
            sa.Column("create_time", sa.BigInteger(), nullable=True),
            sa.PrimaryKeyConstraint("id"),
        )
        op.create_index(
            op.f("ix_life_event_file_id"), "life_event", ["file_id"], unique=False
        )
        op.create_index(
            op.f("ix_life_event_file_type"), "life_event", ["file_type"], unique=False
        )
        op.create_index(
            op.f("ix_life_event_parent_id"), "life_event", ["parent_id"], unique=False
        )
        op.create_index(op.f("ix_life_event_type"), "life_event", ["type"], unique=False)
        # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    # 检查 life_event 表是否存在
    if inspector.has_table("life_event"):
        op.drop_index(op.f("ix_life_event_type"), table_name="life_event")
        op.drop_index(op.f("ix_life_event_parent_id"), table_name="life_event")
        op.drop_index(op.f("ix_life_event_file_type"), table_name="life_event")
        op.drop_index(op.f("ix_life_event_file_id"), table_name="life_event")
        op.drop_table("life_event")
    # ### end Alembic commands ###
